package com.jiyun.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jiyun.bean.StoriesEntity;

import com.jiyun.dao.StoriesEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storiesEntityDaoConfig;

    private final StoriesEntityDao storiesEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storiesEntityDaoConfig = daoConfigMap.get(StoriesEntityDao.class).clone();
        storiesEntityDaoConfig.initIdentityScope(type);

        storiesEntityDao = new StoriesEntityDao(storiesEntityDaoConfig, this);

        registerDao(StoriesEntity.class, storiesEntityDao);
    }
    
    public void clear() {
        storiesEntityDaoConfig.clearIdentityScope();
    }

    public StoriesEntityDao getStoriesEntityDao() {
        return storiesEntityDao;
    }

}
